const donors = [
  {
    id: "1",
    name: "Kamran Warraich",
    bloodGroup: "A+",
    city: "Zostel Inn, Street 7A, Royal Avenue, Islamabad",
    age: "22",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "2",
    name: "Khurram Shahzad",
    bloodGroup: "A-",
    city: "Al-latif lab, Jahanian",
    age: "12",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "3",
    name: "Abrar Warraich",
    bloodGroup: "AB+",
    city: "Jahanian",
    age: "17",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "4",
    name: "Usman Yousaf",
    bloodGroup: "AB-",
    city: "Bahawalpur",
    age: "23",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "5",
    name: "Tayyab Khazain Tahir",
    bloodGroup: "B+",
    city: "Rawalpindi",
    age: "21",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "6",
    name: "Zaman Qadir",
    bloodGroup: "O+",
    city: "Toba tek Singh",
    age: "20",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "8",
    name: "Naveed Ahmed Khan",
    bloodGroup: "O-",
    city: "Gilgit",
    age: "22",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "9",
    name: "Muhammad Bilal",
    bloodGroup: "A+",
    city: "Vehari",
    age: "19",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "10",
    name: "Usama Sadiq",
    bloodGroup: "B+",
    city: "Multan",
    age: "21",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
  {
    id: "11",
    name: "Rao Faizan",
    bloodGroup: "AB-",
    city: "Ali Pur",
    age: "22",
    contact: "03001234567",
    photo: "kami.jpeg",
  },
];

export default donors;
